### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by guidev** [smodin-io/fast-text-language-detection#7]
I get the following error when I run

`npm i @smodin/fast-text-language-detection      
`
                          
```
npm ERR! code 1
npm ERR! path /redacted/project/node_modules/@smodin/fast-text-language-detection
npm ERR! command failed
npm ERR! command sh -c npm-install-fetch
npm ERR! + resource: (@smodin/fast-text-language-detection): FastText LID-176 model
npm ERR! * location: https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
npm ERR! @ download: 131.266.198 bytes received.
npm ERR! npm-install-fetch: ERROR: mkdirp is not a function

npm ERR! A complete log of this run can be found in: ~/.npm/_logs/2023-05-29T19_39_18_292Z-debug-0.log

```

**Comment by GreenCobalt** [comment]
The latest version of `npm-install-fetch` appears to be broken, which this package relies on.
Try installing version 1.3.7 of `npm-install-fetch` manually before trying to install this package (`npm i npm-install-fetch@1.3.7`).

This works for me on Node 18.16.0 LTS.

**Comment by ali-habibzadeh** [comment]
nah, its broken with every single version right up to 1.3.8

**Comment by wizd** [comment]
> The latest version of `npm-install-fetch` appears to be broken, which this package relies on. Try installing version 1.3.7 of `npm-install-fetch` manually before trying to install this package (`npm i npm-install-fetch@1.3.7`).
> 
> This works for me on Node 18.16.0 LTS.

Thanks, it works!

**Comment by guidev** [comment]
fixed in https://github.com/rse/npm-install-fetch/pull/2
